#!/bin/bash
set -e

# Deployment Script for hello-world
# Generated by Forge AI - Phase 10

PROJECT_NAME="hello-world"
IMAGE_TAG="${IMAGE_TAG:-1.0.0}"
REGISTRY="${REGISTRY:-ghcr.io}"
CONTAINER_NAME="${CONTAINER_NAME:-$PROJECT_NAME}"
PORT="${PORT:-3000}"

echo "🚀 Deploying $PROJECT_NAME..."

# Build image
echo "📦 Building Docker image..."
docker build -f deployment/Dockerfile -t $REGISTRY/$PROJECT_NAME:$IMAGE_TAG .

# Stop existing container
echo "🛑 Stopping existing container..."
docker stop $CONTAINER_NAME || true
docker rm $CONTAINER_NAME || true

# Run new container
echo "🏃 Starting container..."
docker run -d \
  --name $CONTAINER_NAME \
  -p $PORT:3000 \
  --restart unless-stopped \
  $REGISTRY/$PROJECT_NAME:$IMAGE_TAG

echo "✅ Deployment complete!"
echo "📍 Container: $CONTAINER_NAME"
echo "🌐 Access at: http://localhost:$PORT"

# Health check
echo "🔍 Running health check..."
sleep 2
if docker ps | grep -q $CONTAINER_NAME; then
  echo "✅ Container is running"
else
  echo "❌ Container failed to start"
  docker logs $CONTAINER_NAME
  exit 1
fi
