#!/bin/bash
set -e

# Rollback Script for hello-world
# Generated by Forge AI - Phase 10

CONTAINER_NAME="${CONTAINER_NAME:-hello-world}"
BACKUP_IMAGE="${BACKUP_IMAGE}"

if [ -z "$BACKUP_IMAGE" ]; then
  echo "❌ Error: BACKUP_IMAGE not specified"
  echo "Usage: BACKUP_IMAGE=ghcr.io/project/app:old-tag ./rollback.sh"
  exit 1
fi

echo "⏮️  Rolling back to: $BACKUP_IMAGE"

# Stop current
echo "🛑 Stopping current container..."
docker stop $CONTAINER_NAME || true

# Restart with backup image
echo "🏃 Starting backup image..."
docker run -d \
  --name $CONTAINER_NAME \
  --restart unless-stopped \
  $BACKUP_IMAGE

echo "✅ Rollback complete!"
