/**
 * Model: Output
 * Generated by ImplementationAgent
 */

export class Output {
  constructor(data = {}) {
    this.success = data.success;
    this.data = data.data;
    this.error = data.error;
  }

  toJSON() {
    return {
      success: this.success,
      data: this.data,
      error: this.error,
    };
  }

  static fromJSON(json) {
    return new Output(json);
  }

  validate() {
    // Validation logic
    return true;
  }
}

export default Output;
