/**
 * Middleware Layer
 * Generated by ImplementationAgent
 */

export const requestLogger = (req, res, next) => {
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.path}`);
  next();
};

export const errorCatcher = (fn) => (req, res, next) => {
  Promise.resolve(fn(req, res, next)).catch(next);
};

export const validateInput = (schema) => {
  return (req, res, next) => {
    // Input validation based on schema
    next();
  };
};

export default { requestLogger, errorCatcher, validateInput };
